apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest-v1
  labels:
    app: webtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtest
      version: "1.0"
  template:
    metadata:
      labels:
        app: webtest
        version: "1.0"
        demo: "5.0"
    spec:
      containers:
        - name: webtest
          image: "erik8scop/webtest"
          ports:
            - name: visitors
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: visitors
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: visitors
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: VERSION
              value: "1.0"
            - name: LIVENESS_WAIT
              value: "0"
            - name: READINESS_WAIT
              value: "0"
            - name: READINESS_CHECK
              value: "true"
