apiVersion: v1
kind: Service
metadata:
  name: webtest
  labels:
    app: webtest
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: webtest
    version: "1.0"